version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
hooks:
  AfterInstall:
  - location: /afterInstall.sh
    timeout: 300 # 5 mins
    runas: root
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu